name: CI

on:
  push:
    branches: [ saikyohopz ]
  pull_request:
    branches: [ saikyohopz ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        sm-version: [ '1.10', '1.11', '1.12' ]

    steps:
      - uses: actions/checkout@v1
      
      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{matrix.sm-version}}

      - name: Setup Dependency for Compiling shavit-zones-http.sp
        run: |
          git clone https://github.com/clugg/sm-json.git;
          cp -r sm-json/addons $GITHUB_WORKSPACE;
          rm -rf ./sm-json;
          git clone https://github.com/ErikMinekus/sm-ripext.git;
          cp -r sm-ripext/pawn/scripting $GITHUB_WORKSPACE/addons/sourcemod;
          rm -rf ./sm-ripext;
          wget https://github.com/hermansimensen/eventqueue-fix/archive/refs/tags/1.3.1.tar.gz;
          tar --strip-components=1 -xvzf 1.3.1.tar.gz -C $GITHUB_WORKSPACE/addons/sourcemod;
          rm -rf ./1.3.1.tar.gz;
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE/addons/sourcemod/scripting;
          for file in s*.sp; do spcomp -i./include $file; done;